# Generated by Django 4.2 on 2023-09-02 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('web', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Distribuidores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('Software', 'Productos de Software'), ('Hardware', 'Productos de Hardware'), ('PC', 'PC`s Armadas'), ('Note', 'Noteboocks'), ('Tablets', 'Tablets')], max_length=8)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='pictures')),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compunet.distribuidor')),
            ],
        ),
    ]
